### ISSUE TITLE
Roadmap: beta-1.0.0

### ISSUE THREAD

**Issue by gwennlbh** [schoolsyst/backend#3]
> This is the roadmap for schoolsyst's first "official" release: `beta-1.0.0` !

- [x] README.md
- [ ] move api.schoolsyst.com/api to /
- [ ] move api.schoolsyst.com/admin to admin.schoolsyst.com
- [x] basics of www.schoolsyst.com
- [x] move from sqlite3 to postgresql
- [x] put django secret key in env variable
- [x] CORS: only allow *schoolsyst.com
- [ ] email verification for account registration
- [ ] Store settings on the user and get rid of `settings-definitions`
- [ ] Switch to a flexible year division strategy (see schoolsyst/frontend#48)
- [ ] Add `updated_at` and `completed_at` fields for all resources
- [ ] Introduce `/quizzes/`
- [ ] Add mongodb-like `?filter`, `?sort`, etc. (see <https://docs.python-eve.org/en/stable/features.html#filtering>)

**Comment by gwennlbh** [comment]
Note that security-related changes are not critical enough to perform an attack: I wouldn't put them here publicly if they were. eg. for now, api.schoolsyst.com's CORS header do not accept anything, and the secret key, although still hard-coded, is not the one in this repo
